# Generated by Django 2.1.4 on 2018-12-07 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SKU', models.CharField(max_length=255)),
                ('NAME', models.CharField(max_length=255)),
                ('LOCATION', models.CharField(max_length=255)),
                ('DEPARTMENT', models.CharField(max_length=255)),
                ('CATEGORY', models.CharField(max_length=255)),
                ('SUBCATEGORY', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'user_data',
            },
        ),
    ]
