# Generated by Django 2.1.4 on 2018-12-07 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inmarapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user_data',
            new_name='UserData',
        ),
    ]
