# Generated by Django 2.1.4 on 2018-12-10 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inmarapp', '0002_auto_20181207_0630'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdata',
            options={},
        ),
    ]
